### ISSUE TITLE
Bridge network inaccessible occasionally after ecs-optimized instance launch

### ISSUE THREAD

**Issue by jamiegs** [aws/amazon-ecs-init#105]
I'm using autoscaling to launch ECS instances and occasionally the containers that are launch on the new host will not have any access to the external network.  I'm able to resolve the issue by restarting docker and starting the ECS agent again.

Looking in the docker logs I see the message 'WARNING: IPv4 forwarding is disabled.', which pointed me to this docker issue and PR which appears to be fixed. https://github.com/moby/moby/issues/490 
https://github.com/moby/moby/pull/1673

However I'm still seeing this occurring on the `amzn-ami-2016.09.f-amazon-ecs-optimized` AMI.

I'm not sure if this is the right place to post this. Please let me know if there's a better place.

**Comment by nmeyerhans** [comment]
Hi @jamiegs. This isn't officially the right place to post this, but it gets seen by the right people, so it'll work.

Docker itself is supposed to take care of enabling IP forwarding. It sounds like there may be a race condition at startup, where (occasionally) something starts after docker and disables it.

The current version of the ECS AMI is `amzn-ami-2017.03.d-amazon-ecs-optimized` and this includes a newer Docker release, as well as a number of updated operating system packages. If possible, it might be worth trying this AMI.

I will investigate the startup configuration on the ECS AMI. My hypothesis is that our Docker init script isn't properly declaring dependencies on network interfaces or services. Are you installing any additional software that may be adjusting the relevant sysctl parameters? I just want to make sure I understand all the actors involved.

**Comment by jamiegs** [comment]
@nmeyerhans  I'll try switching to the new AMI version today and let you know if I'm still seeing the issue over the next several days.

The only software I'm installing is the signalfx collectd agent.  It does feel like it's a race condition because its fairly rare that it happens and a restart of docker fix it.  I am using a cloudformation script to create the cluster. I'm going to compare the script to one from AWS to see if there's maybe something else in there that might be causing this.

**Comment by nmeyerhans** [comment]
I haven't had a chance to look at this in any real depth, but I'm curious about whether the newer Docker releases in our recent AMIs have changed the behavior at all. (17.03.2-ce is the one we're current shipping)

**Comment by jamiegs** [comment]
@nmeyerhans I have switched to the newer AMI, and I haven't seen any issues, however our ECS cluster also hasn't been autoscaling much lately.  I'd be happy with calling this resolved until we start seeing the issues again.

**Comment by nmeyerhans** [comment]
Ok, please feel free to reopen this issue if the problem recurs. Thanks.
