### ISSUE TITLE
Disabling ecs

### ISSUE THREAD

**Issue by bryanl** [aws/amazon-ecs-init#106]
With the version of Upstart installed on Amazon Linux, you can't disable ecs using an override file. Would it be possible to move it `chkconfig`? Or, is there something I'm missing with disabling the service?

**Comment by jhaynes** [comment]
Hi @bryanl. Thanks for your question. On our AMIs we run upstart 0.6.5 which doesn't accept the current `manual` stanza. It will allow an override file though. See the [upstart cookbook](http://upstart.ubuntu.com/cookbook/#override-file) for more details. If you override the start run levels, ecs will not start on reboot:
```
echo start on stopped rc RUNLEVEL=[] | sudo tee /etc/init/ecs.override
```
Alternatively, you can edit the `/etc/init/ecs.conf` file or rename it.

**Comment by jhaynes** [comment]
@bryanl We haven't heard back from you in a few days so I'm going to close this. However, if you still have questions, feel free to re-open this issue, create a new one, or engage AWS Support directly.
