### ISSUE TITLE
http proxy settings ignored in /etc/init/ecs.override

### ISSUE THREAD

**Issue by lukasbernat** [aws/amazon-ecs-init#108]
ecs.override:
        echo "HTTP_PROXY=$PROXY_HOST:$PROXY_PORT" >> /etc/init/ecs.override
        echo "HTTPS_PROXY=$PROXY_HOST:$PROXY_PORT" >> /etc/init/ecs.override
        echo "NO_PROXY=169.254.169.254,169.254.170.2,/var/run/docker.sock" >> /etc/init/ecs.override

ecs-init fails to download the ecs-agent:
2017-08-08T19:49:57Z [ERROR] could not download Amazon EC2 Container Serivce Agent: Get https://s3.amazonaws.com/amazon-ecs-agent/ecs-agent-v1.14.3.tar.md5: dial tcp 52.216.16.219:443: i/o timeout
(proxy access log does not show this request)

when I set http_proxy env variables, ecs-init does download the ecs-agent properly. but since this is problematic during OS boot, I am wondering if there is an alternate way doing this. documentation isn't very clear how this is supposed to work. tried
http://docs.aws.amazon.com/AmazonECS/latest/developerguide/http_proxy_config.html
with no luck.

**Comment by samuelkarp** [comment]
It looks like we need to make our documentation more clear.  Environment variables in an Upstart override file need to be preceded by `env`: http://upstart.ubuntu.com/cookbook/#environment-variables

I think this should do what you want:

```bash
cat <<EOF >/etc/init/ecs.override
env HTTP_PROXY=$PROXY_HOST:$PROXY_PORT
env HTTPS_PROXY=$PROXY_HOST:$PROXY_PORT
env NO_PROXY=169.254.169.254,169.254.170.2,/var/run/docker.sock
EOF
```

**Comment by lukasbernat** [comment]
worked, thanks
