### ISSUE TITLE
[QUESTION] Where can the Ubuntu deb package be accessed?

### ISSUE THREAD

**Issue by pantocrator27** [aws/amazon-ecs-init#116]
Is the deb package for Ubuntu published somewhere?  If so where?

Thanks!

**Comment by vsiddharth** [comment]
As far as I am aware, we don't publish the deb package.

**Comment by daytonpa** [comment]
Is there a way to use this repo and install the ecs-init package on Ubuntu?  I've been trying to install this for hours with no success, and the docs don't provide much information on setting it up.

**Comment by samuelkarp** [comment]
@pantocrator27 @daytonpa We do not currently publish the deb package.  If you'd like to install it, you'll need to clone this repository and run `make ubuntu-trusty` to generate a deb locally.
