### ISSUE TITLE
testing with suse, ubuntu tags

### ISSUE THREAD

**Issue by adnxn** [aws/amazon-ecs-init#131]
Today we aren't exercising test paths for non amazon linux operating systems.
Running `go test -short -v -cover -tags suse ./...` and `go test -short -v -cover -tags ubuntu ./...` results in test failures for `TestStartAgentNoEnvFile` and `TestStartAgentEnvFile`.

We should fix these and also add the tagged test runs to our CI.

**Comment by ellenthsu** [comment]
closing this item as it's not an item the team will be working on in the near future
