### ISSUE TITLE
Upstart service doesn't respawn

### ISSUE THREAD

**Issue by wild-endeavor** [aws/amazon-ecs-init#135]
I'm trying to use the this package as an upstart service but it doesn't seem to be resilient to docker daemon restarts. 
```
$ uname -a
Linux some-host-name 3.13.0-135-generic #184-Ubuntu SMP Wed Oct 18 11:55:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

ytong@some-host-name:~$ initctl status ecs
ecs start/running, process 48412
ytong@some-host-name:~$ sudo service docker restart
docker stop/waiting
docker start/running, process 50427
ytong@some-host-name:~$ initctl status ecs
ecs stop/waiting
```

Restarting the docker daemon puts the ecs-init daemon into a stop/waiting state.  The actual ecs-agent container remains running, but I'd like the ecs-init service to also be running.  I've tried tweaking the `ecs.conf` file but I don't seem to be able to get the right combination of respawn and expect.  Do you guys have any ideas?

Thank you.

**Comment by wild-endeavor** [comment]
@samuelkarp any ideas on this?

**Comment by pabloqc** [comment]
@wild-endeavor Could you check your etc/ecs/ecs.config file?
I had a similar issue and the reason was because of a mismatch with the cluster-name. If by any change you modify your ECS_CLUSTER key and it doesn't match with the one that you get with:
curl http://localhost:51678/v1/metadata then the ecs agent won't be able to start.

**Comment by fierlion** [comment]
For this functionality, I'd recommend upgrading to Amazon Linux 2 which uses systemd as its init process.  Given the limitations of the version of upstart in Amazon Linux 1, it will be significant effort to define the `depends on` relationship between dockerd and ecs-init.  At this point I don't see how it's possible but I'm still looking into possible solutions.  
See my detailed analysis of ecs-init and docker with these respective init systems:
https://github.com/aws/amazon-ecs-init/issues/231
