### ISSUE TITLE
Support alternative docker endpoints

### ISSUE THREAD

**Issue by tomwilkie** [aws/amazon-ecs-init#14]
Hi there - would you be open to a PR to allow ecs-init to read the location of the docker endpoint out of the config file?

**Comment by euank** [comment]
Sounds like a good idea to me, though it might make sense to use the more canonical environment variable DOCKER_HOST in addition to just a config file option.

PR welcome, thanks!

**Comment by tomwilkie** [comment]
Agreed, environment better in this case.

**Comment by samuelkarp** [comment]
I've just merged #17, so this is now pending release.

**Comment by samuelkarp** [comment]
This was released a while ago with https://github.com/aws/amazon-ecs-init/releases/tag/v1.3.1-1.  Closing.
