### ISSUE TITLE
No ecs-init package available in Amazon Linux 2

### ISSUE THREAD

**Issue by rajbettaswamy** [aws/amazon-ecs-init#149]
### Summary
No ```ecs-init``` package available in yum repository on Amazon Linux 2.

### Expected Behavior
Should install ```ecs-init``` package.

### Observed Behavior
```
bash-4.2# yum install ecs-init
Loaded plugins: ovl, priorities
amzn2-core                                               | 2.0 kB     00:00
No package ecs-init available.
Error: Nothing to do
```

### Environment Details
OS: Amazon Linux 2 (amazonlinux:2017.12)
Kernel: 4.9.60-linuxkit-aufs

**Comment by austinbutler** [comment]
Also there's no Amazon Linux 2 AMI for ECS, although I am not sure where that would be reported.

**Comment by arnoldad** [comment]
A big +1 Here. We're holding off on making some architectural decisions until we can get a sense for an ETA for the AL2. Even a pre-release AMI would be massively helpful for us to test in non-production tiers.

**Comment by talawahtech** [comment]
@jhaynes it would be great if you guys could also provide a repo with the packer scripts used to build the AL2 based ECS Opimized AMI. Something similar to what EKS has: https://github.com/awslabs/amazon-eks-ami

This would allow us even further for flexibility in customizing our AMIs while still maintaining close compatibility with the official images. For example I am not sure if there is currently a way to **reduce** the size of the /dev/xvdcz block device below the default of 22GB while still using the ECS Optimized AMI as the base image.

Any updates on the new AL2 compatible package and AMI? Is this something we are likely to see before re:invent?

**Comment by jahkeup** [comment]
We happy to report there is now an `ecs-init` package for Amazon Linux 2 which accompanies the [Amazon ECS-Optimized Amazon Linux 2 AMI](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/al2ami.html)!

The `ecs-init` package, as in the prior versions of Amazon Linux, provides the necessary support for the Amazon ECS container agent and on AL2 the `ecs.service` provides greater reliability with its inter-dependency support provided by systemd. On instances already running Amazon Linux 2, users can enable the `ecs` [Amazon Linux Extra](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/amazon-linux-ami-basics.html#extras-library) and install the `ecs-init` package (the ECS-Optimized AMI provides a pre-configured image ready for use with the extra and `ecs-init` already setup).

For Amazon Linux 2 installation instructions, please [visit the Amazon ECS documentation site](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-install.html#ecs-agent-install-al2).

**Comment by talawahtech** [comment]
@jahkeup this is awesome, I just tried it out but I ran into an issues.

From the [storage configuration](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/al2ami-storage-config.html) docs I see you guys are now using a single root volume with OverlayFS which is great. The docs specifically mention the following"

> the Amazon ECS-optimized Amazon Linux 2 AMI ships with a single 30 GiB root volume, with a base snapshot size of 2 GiB. You can modify the 30 GiB root volume size at launch time to increase or decrease the available storage on your container instance.

Which I took to mean that you could now launch with a root volume that is less than 30GB, however when trying to do so via the console or CloudFormation I get the following error:

> volume of size 20GB is smaller than snapshot 'snap-0d543bf20c182e7f4', expect size >= 30GB

Am I misinterpreting the docs or should there be a way to launch an instance with a 20GB volume?

**Comment by jahkeup** [comment]
@talawahtech unfortunately, the AMI's snapshot does not allow you to resize down despite the doc's text. We'll get these docs updated ASAP to reflect this. Sorry about the confusion!

**Comment by talawahtech** [comment]
@jahkeup Thanks for the quick response. So what would be the next best way to achieve what I am trying to do? If I start with the `amzn2-ami-minimal-hvm-2.0.20181008-x86_64-ebs` AMI and then enable the ECS extras repo and install/enable/start the ecs service do I end up with essentially the same image? Or is there some additional secret sauce in terms of configuration files or additional packages?

I see that the amzn2extra-ecs repo has its own docker package so I guess I would disable the amzn2extra-docker repo and let ecs-init pull in its own version as a dependency. So my theoretical user data script would look something like this:

```
amazon-linux-extras disable docker
amazon-linux-extras enable ecs
yum install -y ecs-init
systemctl enable ecs
systemctl start ecs
```
What else would I be missing?

**Comment by jahkeup** [comment]
@talawahtech there's some explanation [in the docs regarding installing on an AL2 instance](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-install.html#ecs-agent-install-al2); it roughly boils down to what you've outlined.

If I may offer a quick tip: the `amazon-linux-extras` tool can install the "right" packages for the extra you're operating on!

```bash
amazon-linux-extras disable docker
amazon-linux-extras install -y ecs
$configure_ecs_steps
systemctl enable --now ecs
```

**Comment by talawahtech** [comment]
Great, that is exactly what I was looking for, thanks! One thing though, the [storage docs state](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/al2ami-storage-config.html) that ext4 is used in the ECS Optimized AMI, whereas the regular Amazon Linux 2 AMIs ship with xfs, so when these instructions are followed I end up with more or less the same software, but a different filesystem. 

Was there some performance or stability benefit to ext4 + overlay2 why that was chosen over xfs + overlay2?

**Comment by talawahtech** [comment]
Also one last (hopefully) thing. These 3 packages seem to be installed on the Optimized AMI but not the Amazon Linux 2 minimal AMI. Any of them crucial?

```
acpid
ec2-net-utils.noarch
yum-plugin-upgrade-helper
```

**Comment by jahkeup** [comment]
@talawahtech I'd install `ec2-net-utils` as its udev rules are crucial for the operation of the awsvpc network mode.

**Comment by talawahtech** [comment]
@jahkeup Thanks, that's helpful since I was planning to use awsvpc mode. Should I create a github issue for it to be a dependency of the ecs-init package?

Any comment on the ext4 vs xfs question?

**Comment by talawahtech** [comment]
@jahkeup done: https://github.com/aws/amazon-ecs-init/issues/202

Thanks for all the helpful responses.

**Comment by Buuntu** [comment]
Is there any plan to add Docker 18.09 as a dependency to ecs-init soon?  Having trouble running a certain Docker file on AWS Batch due to this error: 
```CannotPullContainerError: failed to register layer: Error processing tar file(exit status 1): unexpected EOF```
which I think relates to this issue: https://github.com/docker/for-mac/issues/2388.  I only get the error on Docker 18.06

**Comment by jahkeup** [comment]
@Buuntu can you open a new issue to track and investigate this error? 

From a quick perusal of the linked issue it seems like https://github.com/moby/moby/issues/37581 is the driving upstream bug report. The issue suggest to me that if you're using an image that has large layers then its likely the cause - but do open an issue and get some details on the environment posted. Thanks!
