### ISSUE TITLE
use s3 client instead of http client to download images

### ISSUE THREAD

**Issue by aaithal** [aws/amazon-ecs-init#157]
### Summary

use s3 client instead of http client to download images

### Description

The `Downloader` uses `http` client to download the ECS agent tarball. It should use s3 client instead:
 https://github.com/aws/amazon-ecs-init/blob/24c976b4e04a369e8f25f7c48f159d712623824f/ecs-init/cache/cache.go#L39

**Comment by samuelkarp** [comment]
If we move to the S3 client, we'll need to make sure to use `credentials.AnonymousCredentials` so we don't require the instance to have S3 permissions.

```go
svc := s3.New(session.Must(session.NewSession(&aws.Config{
  Credentials: credentials.AnonymousCredentials,
})))
```

**Comment by aaithal** [comment]
We've released a new [version of the ECS init](https://github.com/aws/amazon-ecs-init/releases/tag/v1.17.3-1), which should fix this issue. Closing this for now.
