### ISSUE TITLE
Use a top level CHANGELOG to record version's changes

### ISSUE THREAD

**Issue by jahkeup** [aws/amazon-ecs-init#162]
It would be great to have a top level `CHANGELOG.md` file to record significant changes to be reported in packaging and source distribution of the code here. See the [amazon-ecs-agent's for example](https://github.com/aws/amazon-ecs-agent/blob/master/CHANGELOG.md). Pull requests would include a change to this file to ensure that no changes are forgotten when releases are cut.

**Comment by fierlion** [comment]
Proposal: we add the same CHANGELOG process for ecs-init that we have for https://github.com/aws/amazon-ecs-agent

**Comment by fierlion** [comment]
https://github.com/aws/amazon-ecs-init/pull/295
