### ISSUE TITLE
IMPORTANT: Broken ecs-init-1.17.3 on @amzn-updates.

### ISSUE THREAD

**Issue by omeid** [aws/amazon-ecs-init#163]
Greetings,

Today my ECS Instances stopped connecting to my ECS Cluster after scheduled updates, the culprit seems to be a ecs-init-1.17.3 pushed to @amzn-update repository. 

It seems to have been caused by 77120e3 which I am not sure how it has landed there to begin with! it is detached from the master and no release has been tagged, how could it land on @amazn-updates?

**Comment by omeid** [comment]
I am sorry but I just checked and `ecs-init-1.17.3` is still in `@amzn-updates`. 

Also, how did this all happen? How can a single detached commit without a release tag cause a release that ends up in `@amzn-updates`?

**Comment by nmeyerhans** [comment]
@omeid, to clarify, ECS Agent 1.17.3 is now available, so ecs-init-1.17.3 from the \@amzn-updates repository works. See the [agent release](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.17.3) for details on that.

As to how ecs-init-1.17.3 was created before the PR was merged, our release process involves building and testing the packages before we actually merge the change. This way if we do need to make any updates to the candidate, we can do so without worrying about invalidating tags or GitHub releases. When the package is released, its corresponding commit is merged into master and tagged appropriately.

**Comment by omeid** [comment]
Thanks for the clarification Noah,

I think a little more visibility into the release process would be helpful.

As you can see I am _watching_ this repository and yet had no idea to expect an update and it was a fair bit of debugging frustration to find out what is exactly going on.

Have a great weekend.

**Comment by clickthisnick** [comment]
@aaithal @nmeyerhans Thank you for the information!

Our servers were affected by this, but we don't have any automatic yum cron updates running.
Does ECS update its services with the latest ECS Agent? Is there a way to stop this from happening?

**Comment by bbb31** [comment]
We experienced this bug as well through our automated security patching process. Unfortunately, it didn't end too well.
