### ISSUE TITLE
SUSE systemd unit missing appropriate stop, post-stop directives

### ISSUE THREAD

**Issue by jahkeup** [aws/amazon-ecs-init#182]
### Summary

The SUSE systemd unit is missing the directives now present and accounted for in the AL2 systemd unit.

**Comment by fierlion** [comment]
https://github.com/aws/amazon-ecs-init/blob/master/packaging/suse/amazon-ecs.service

**Comment by fierlion** [comment]
https://github.com/aws/amazon-ecs-init/blob/master/packaging/amazon-linux-ami/ecs.service#L29-L30

**Comment by jahkeup** [comment]
@fierlion not sure what's meant with these links, I think there's still differences present here though I'm somewhat removed from on going work in `ecs-init` at this point. From a quick glance, I do see that we're not calling the same subcommands that we're calling and using in AL2 (which was what this issue was opened to address). We should test/get-confirmations that the service works correctly and behaves similarly on OpenSUSE as it does in AL2.

**Comment by fierlion** [comment]
Sorry.  See updates to my comment above.

**Comment by jahkeup** [comment]
Okay, I got it :+1: 

So the real outstanding task here is to actually go and test it before we commit that change (which I think was the reason why I deferred the effort to an issue long, long ago..).

**Comment by samuelkarp** [comment]
https://build.opensuse.org/package/show/openSUSE:Factory/amazon-ecs-init appears to be the place where the OpenSUSE build is produced.  @rjschwei is the maintainer who had been helping us package ecs-init for that distro.

**Comment by fierlion** [comment]
> So the real outstanding task here is to actually go and test it before we commit that change (which I think was the reason why I deferred the effort to an issue long, long ago..), is that right?

that's right.  I'll update here with my manual test results on SUSE.

**Comment by fierlion** [comment]
https://github.com/aws/amazon-ecs-init/pull/285

**Comment by rjschwei** [comment]
https://build.opensuse.org/package/show/openSUSE:Factory/amazon-ecs-init is the derived package for release with openSUSE Tumbleweed which will eventually make it's way into openSUSE Leap and SLE. Development of the package happens here:

https://build.opensuse.org/package/show/Cloud:Tools/amazon-ecs-init

**Comment by fierlion** [comment]
Merged.  I'll open a follow-up issue to work through the `make rpm` target and the suse spec file.  `make rpm` is pinned to amazon-linux and the suse spec file hasn't been updated in a while and requires attention.
