### ISSUE TITLE
Please don't use dashes in version numbers

### ISSUE THREAD

**Issue by glaubitz** [aws/amazon-ecs-init#183]
The current upstream version of amazon-ecs-init contains a dash in its version numbers which can cause problems when packaging the software downstream.

Trying to build 1.18.0-1 on openSUSE bails out with the following error:

```
[    3s] + exec rpmbuild -ba --define '_srcdefattr (-,root,root)' --nosignature /home/abuild/rpmbuild/SOURCES/amazon-ecs-init.spec
[    3s] error: line 21: Illegal char '-' (0x2d) in: Version:        1.18.0-1
[    3s] 
[    3s] suse-laptop failed "build amazon-ecs-init.spec" at Tue Jul 17 11:25:49 UTC 2018.
[    3s]
```

Most distribution package managers use the number after the dash to indicate the package revision in the distribution, so upstream vendors should avoid using version numbers that include dashes.

While downstream distributions can just remove the dash from the version string and set the version ```1.18.0```, at least on openSUSE this means the upstream tarball will have to be repacked such that the source folder is called ```amazon-ecs-init-1.18.0``` which will destroy the checkum of the upstream tarball.

**Comment by jahkeup** [comment]
@glaubitz I see the issue in the [spec (and its workaround)](https://build.opensuse.org/package/view_file/Cloud:Tools/amazon-ecs-init/amazon-ecs-init.spec?expand=1&rev=23). This repo's tagging today tags the Amazon Linux version-release of the release NVR. Though this tag format may not change in the near future, this topic is certainly worth talking about and we'll track this internally for review.

Thank you for the issue, I'll be sure to ping back.

**Comment by fierlion** [comment]
We’ve internally evaluated the risk of changing our version scheme and have chosen to follow our present convention.
