### ISSUE TITLE
ecs agent unable to update via cli 

### ISSUE THREAD

**Issue by MattRiches** [aws/amazon-ecs-init#191]
**Summary**
Unable to update ecs agent to latest verson via cli 

**Description**
When updating via the console, it successfully updates ecs-init to latest version, via yum:
$ yum install ecs-init                                                                                                                                                        
Package ecs-init-1.19.1-1.amzn1.x86_64 already installed and latest version.

$ curl -s 127.0.0.1:51678/v1/metadata | python -mjson.tool
"Version": "Amazon ECS Agent - v1.19.1 (13a0fabe)"

In the console: 
Outdated ECS Agent
One or more container instances are not running the latest version of the Amazon ECS container agent

**Comment by jahkeup** [comment]
Hi @MattRiches, the latest `ecs-init` package isn't available yet in the Amazon Linux repos. We're working to have it available as soon as possible. Sorry for the confusion! I'll be sure we chime in here again when it is.

**Comment by MattRiches** [comment]
No worries, thank you.

**Comment by MattRiches** [comment]
Hey @jahkeup  - any update on this?

**Comment by jahkeup** [comment]
Hey @MattRiches, the package is now live! Thanks for your patience. Please feel free to ping again if there are any further issues.
