### ISSUE TITLE
Missing dependency on ec2-net-utils

### ISSUE THREAD

**Issue by talawahtech** [aws/amazon-ecs-init#202]
### Summary
According to @jahkeup ec2-net-utils' udev rules are crucial for the operation of the awsvpc network mode, however the package is not included as a dependency of ecs-init and is therefore not automatically installed.

### Description
I followed the [documented instructions](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-install.html#ecs-agent-install-al2) for installing ecs-init on Amazon Linux 2.

### Expected Behavior
ec2-net-utils should be installed automatically or it should be noted in the documentation as a dependency.

### Observed Behavior
ec2-net-utils was not automatically installed.

### Environment Details
AMI ID: amzn2-ami-hvm-2.0.20181008-x86_64-gp2

**Comment by jahkeup** [comment]
@talawahtech I had a chat offline with folks regarding the use of `ec2-net-utils` in the context of Amazon Linux and ECS. I was mistaken: this package itself isn't required for operation of the `awsvpc` network mode. The ECS container agent does rely on udev at runtime but [manages the required events itself](https://github.com/aws/amazon-ecs-agent/blob/e8b5229a9ea8b748ebad4db4c098ccc8df2dcd5f/agent/eni/watcher/watcher_linux.go) without the aid of external udev rules. 

The `ec2-net-utils` package gives customers consistent device handling when attaching their own ENIs on their instances (eg: not with `awsvpc` mode where this is managed by the ECS container agent). Though the `ec2-net-utils` package is certainly useful, the `ecs-init` package does not have a direct dependency and therefore shouldn't have it expressed as such in the packaging.
