### ISSUE TITLE
Configuration file /usr/lib/systemd/system/ecs.service is marked executable

### ISSUE THREAD

**Issue by talawahtech** [aws/amazon-ecs-init#205]
### Summary
There is a warning in /var/log/messages about ecs.service being marked executable.

### Description
Lookin through /var/log/messages I see the following warning:

`systemd: Configuration file /usr/lib/systemd/system/ecs.service is marked executable. Please remove executable permission bits. Proceeding anyway.`

### Expected Behavior
ecs.service shouldn't be executable (according to the warning at least)

### Observed Behavior
ecs.service is ececutable

### Environment Details
Amazon Linux 2 ECS Optimized AMI
ecs-init 1.21.0

**Comment by fierlion** [comment]
confirmed with latest release https://github.com/aws/amazon-ecs-init/releases/tag/v1.35.0-1 this message is no longer showing in /var/log/messages.
Closing
