### ISSUE TITLE
`docker stop ecs-agent` does not prevent the agent from restarting on Amazon Linux 2

### ISSUE THREAD

**Issue by samuelkarp** [aws/amazon-ecs-init#227]
### Summary
`docker stop ecs-agent` does not prevent the agent from restarting on Amazon Linux 2

### Description
On Amazon Linux (and the old Upstart config), we had it set up so that normal exits (exit code of 0) would not cause Upstart to restart ecs-init (and consequently the agent).  This gave customers two paths to stopping: using `docker stop ecs-agent` (which meant they didn't need to know anything about Upstart) and `sudo stop ecs` (using Upstart).  It doesn't look like we preserved this behavior for Amazon Linux 2 with our systemd unit.

### Expected Behavior
```
$ docker stop ecs-agent
$ sudo systemctl status ecs.service
● ecs.service - ECS Agent
   Loaded: loaded (/usr/lib/systemd/system/ecs.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Fri 2019-01-04 19:36:38 UTC; 2s ago
```

### Observed Behavior
```
$ docker stop ecs-agent
$ sudo systemctl status ecs.service
● ecs.service - ECS Agent
   Loaded: loaded (/usr/lib/systemd/system/ecs.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2019-01-04 19:35:58 UTC; 4s ago
$ sudo systemctl status ecs.service
● ecs.service - ECS Agent
   Loaded: loaded (/usr/lib/systemd/system/ecs.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2019-01-04 19:36:08 UTC; 3s ago
```

### Environment Details
ami-0c1f4871ebaae6d86

**Comment by fierlion** [comment]
confirmed fixed with latest release https://github.com/aws/amazon-ecs-init/releases/tag/v1.35.0-1
output from an instance of the latest ecs-optimized AMI:
```
$ docker stop ecs-agent
ecs-agent
$ sudo systemctl status ecs.service
● ecs.service - Amazon Elastic Container Service - container agent
   Loaded: loaded (/usr/lib/systemd/system/ecs.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Fri 2019-12-20 16:38:14 UTC; 7s ago
```
