### ISSUE TITLE
ECS init 1.25.3 not yet available from repo

### ISSUE THREAD

**Issue by austinbutler** [aws/amazon-ecs-init#237]
### Summary
ECS tells me my agent is outdated even though I have run `sudo yum update` and rebooted. Using the "update agent" button in the console does somehow update it.

### Expected Behavior
Updating the packages via yum updates to the latest version of `ecs-init`.

### Observed Behavior
Updating the packages via yum does not update to the latest version of `ecs-init`.

### Environment Details
```
[ec2-user@ip ~]$ yum info ecs-init | grep Version
Version     : 1.25.2
```

```
[ec2-user@ip ~]$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

**Comment by fierlion** [comment]
We're aware of the issue and working to have updated packages made available. I'll update the issue as soon as it is resolved. In the mean time, the latest ecs-optimized AMI has the most recent 1.25.3 ecs-init and ecs-agent pre installed. You can find the specific ami ids [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/al2ami.html).

**Comment by fierlion** [comment]
this was released yesterday for AL2.  We are now on version 1.26.0

```
[ec2-user@ip-10-0-1-23 ~]$ yum info ecs-init | grep Version
Version     : 1.26.0
```

**Comment by koobe1402** [comment]
ECS init 1.32.0 not yet available from repo

`[root@ip-10-2-12-116 yum.repos.d]# yum info ecs-init | grep Version
Version     : 1.30.0
[root@ip-10-2-12-116 yum.repos.d]# cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"`

**Comment by ellenthsu** [comment]
Thanks for reporting this, we are working to get this resolved
