### ISSUE TITLE
Container labels are not available for configuration

### ISSUE THREAD

**Issue by morfien101** [aws/amazon-ecs-init#259]
### Summary

When running the ECS-Agent using AWS Linux for ECS you are not able to configure labels for the container. We use the labels for logging and grouping.

### Description

The container for ECS-Agent doesn't have the ability to set the docker container labels.

### Expected Behavior

There should be a mechanism to set the labels for the container. This can be injected at user-data boot time.

**Comment by morfien101** [comment]
Are PRs and Issues not being looked at on this repo?

@sparrc Since you where the last person to commit something, can you answer the above question?

**Comment by sparrc** [comment]
Thanks for the contribution and sorry for the delay looking at this, we had internal tickets that took priority. We are currently looking at this as a feature request and reviewing the PR, will let you know soon.

**Comment by morfien101** [comment]
Hi @sparrc Any chance of an update on this PR. We would really like to see it get merged as its currently causing an issue for us.

**Comment by morfien101** [comment]
:rolling_eyes: I pressed the wrong button and closed it. Its actually still open...

**Comment by fenxiong** [comment]
This has been released in [v1.32.1](https://github.com/aws/amazon-ecs-init/releases/tag/v1.32.1-1)
