### ISSUE TITLE
ecs-init-1.33.0-1 is not include in amzn-updates repository yet

### ISSUE THREAD

**Issue by SypherSu** [aws/amazon-ecs-init#270]
### Summary
ecs-init-1.33.0-1 is not include in amzn-updates repository yet

### Description
I found that ecs-init-1.33.0-1 is not in amzn-updates, therefore I could not use AWS CLI "update-container-agent" to update my ECS agent to v1.33.0

### Environment Details
AMI: amzn-ami-2017.03.d-amazon-ecs-optimized

**Comment by petderek** [comment]
The update-container-agent API operates independently of the amzn-updates repositories. Running that API instructs init to pull a signed agent container from S3. 

If you received an error from the API, it was most likely related to [this issue](https://github.com/aws/amazon-ecs-agent/issues/2287). Please let us know if you are still seeing issues.
