### ISSUE TITLE
Print stack trace when Agent crashes

### ISSUE THREAD

**Issue by fenxiong** [aws/amazon-ecs-init#271]
### Summary

Currently when the Agent crashes, the stack trace won't be available in agent logs files, but will be available in Docker container logs (e.g. via `docker logs <container_id>`). However, whenever the agent crashes, the service (on AL2) or upstart job (AL1) is restarted and the previous agent container is removed, and the stack trace is then no where to be found. This makes debugging an agent crash very difficult, especially when the crash is reported by customer.

Also, AFAIK Go doesn't allow catching panic of all the goroutines from a single thread, so the agent can't catch panic and print the stack trace in a single place. So i think ecs init is the only place to get the stack trace and print it.

### Description

I think this can probably be done by calling `docker logs` and print the content from the first line that does not start with `TIMESTAMPE [LOG_LEVEL]` (the format of normal agent logs). Other ways may work as well.

### Expected Behavior

We are able to see the stack trace somewhere when agent crashes.

### Observed Behavior

We are not able to see the stack trace anywhere when agent crashes.

**Comment by petderek** [comment]
The agent restart should happen on ALAMI as well, right? Or do you mean ecs-init isn't restarted?

One way to fix this would be to handle log rotation outside of agent's execution. Agent is currently responsible for writing its own log file, which is problematic in this case.

**Comment by fenxiong** [comment]
> The agent restart should happen on ALAMI as well, right? 

Yeah that's right. I think ALAMI has the same issue. updated the description

**Comment by fierlion** [comment]
My initial plan is to capture a fixed window of the logs using tail, so we don't end up filtering potentially massive log files to capture the failure.  
The risk would be missing the failure altogether if the window is too small. 
From the Docker API docs:
```
since – UNIX timestamp (integer) to filter logs. Specifying a timestamp will only output log-entries since that timestamp. Default: 0 (unfiltered)
timestamps – 1/True/true or 0/False/false, print timestamps for every log line. Default false.
tail – Output specified number of lines at the end of logs: all or <number>. Default all.
```
https://docs.docker.com/engine/api/v1.23/

I think tail with a configurable window is a sane place to start with this.

**Comment by fierlion** [comment]
https://github.com/aws/amazon-ecs-init/pull/273
