### ISSUE TITLE
Unable to start tasks with awsvpc trunking for App mesh.

### ISSUE THREAD

**Issue by vennemp** [aws/amazon-ecs-init#319]
### Summary
Unable to start tasks with awsvpc trunking for App mesh.
### Description
I have a custom AMI that I built based off of the CIS Level 1 marketplace AMI for Amazon Linux 2.  I have manually added the ECS agent following AWS documentation.  Tasks without app mesh and using default network mode work fine on the same ami.  I believe the issue is I need to add ECS_ENABLE_TASK_ENI=true to the ecs.config file.  I have done that via user data however the value is not being reflected when I view the container instance attributes for ecs.. it just says EMPTY VALUE on that attribute..  What am I missing?

**Comment by vennemp** [comment]
I solved this.  I was missing the ecs-init package from my ami.  YOU SHOULD UPDATE THE OFFICIAL AWS DOCUMENTATION FOR THIS.

**Comment by kiranmeduri** [comment]
Thanks for reporting! We will update the documentation to recover this.

**Comment by samuelkarp** [comment]
Instructions for installing the ECS agent on Amazon Linux 2 are available here: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-install.html#ecs-agent-install-al2.  These instructions include installing the `ecs-init` package from the Amazon Linux 2 `ecs` Extra:

> 4. Install and enable the `ecs` Amazon Linux extra repository.
>
> ```
> [ec2-user ~]$ sudo amazon-linux-extras install -y ecs; sudo systemctl enable --now ecs`
> ```

**Comment by vennemp** [comment]
Hey thanks Sam - I must have found some old documentation.  Sorry for yelling.. I was up late and frustrated at that point.  Thanks for your support!
