### ISSUE TITLE
Installation of ecs volume plugin on RHEL

### ISSUE THREAD

**Issue by jeremietharaud** [aws/amazon-ecs-init#344]
### Summary

Unable to install the amazon-ecs-volume-plugin on non-amazon linux distro

### Description

Hi guys, I have installed the ECS agent on a custom AMI based on RHEL (7.8)  by following this [documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-install.html#ecs-agent-install-nonamazonlinux), but I'm stucked with the installation of the amazon-ecs-volume-plugin docker plugin.

### Expected Behavior

amazon-ecs-volume-plugin docker plugin installed (systemd service + socket)

### Observed Behavior

```
$ systemctl enable --now amazon-ecs-volume-plugin
Failed to execute operation: No such file or directory
```
There is no systemd service and socket corresponding to amazon-ecs-volume-plugin.

### Environment Details
RHEL 7.8
````
$ docker info
  Server Version: 19.03.6
....

$ curl http://localhost:51678/v1/metadata
{ "Cluster": "c...","ContainerInstanceArn":"arn:aws:ecs:eu-west-1:....:container-instance/....","Version":"Amazon ECS Agent - v1.43.0 (1ebf0604)"}
````

**Comment by petderek** [comment]
The short answer here is that we don't have a simple ready-to-go solution for running the plugin on any non-optimized AMI right now. I'll mark this as a feature request to do that.

If you aren't using the encryption or IAM / Access Points features, you don't need the plugin. The agent will use docker's built-in nfs driver if only "filesystemId" and "rootDirectory" are set. If you have trouble doing this, please let us know.

The plugin is packaged and installed with amazon-ecs-init on the Amazon linux variants. You can likely reuse the systemd units [here](https://github.com/aws/amazon-ecs-init/tree/master/packaging/amazon-linux-ami) and build the plugin yourself [here](https://github.com/aws/amazon-ecs-init/tree/master/ecs-init/volumes), but we haven't explicitly tested this on RHEL.

You will also need to install the [EFS helper and stunnel](https://docs.aws.amazon.com/efs/latest/ug/using-amazon-efs-utils.html), which the pliugin calls.

**Comment by jeremietharaud** [comment]
@petderek Thank you very much for these useful information. 
OK I will try these solutions and let you know if I face any issue.

**Comment by angelcar** [comment]
Closing. Feel free to reopen if needed.
