### ISSUE TITLE
ECS Agent update issue

### ISSUE THREAD

**Issue by subhas81** [aws/amazon-ecs-init#358]
### Summary
 ECS agent update issue 

### Description
Even after applying the ECS agent in Amzon Linux-2, it is not picking the latest version(1.44.4)
[ec2-user ~]$ sudo yum update -y ecs-init
sudo systemctl restart docker

### Expected Behavior
It should show 1.44.4

### Observed Behavior
It is showing 1.44.3

[root@ip-172-31-30-89 ~]# curl -s 127.0.0.1:51678/v1/metadata | python -mjson.tool

    "Version": "Amazon ECS Agent - v1.44.3 (33b647b8)"
}

**Comment by sparrc** [comment]
yum repos are not controlled by the ecs-agent team. They have a biweekly release cadence which are sometimes delayed.

I can confirm that 1.44.3 is that latest version that I also see in the amazon linux yum repos.

If you'd like to upgrade faster, I'd suggest launching with the latest AMI, upgrading via our dockerhub image, or upgrading via the UpdateContainerAgent API.
