### ISSUE TITLE
iptables rule isn't removed on service restart after changing ECS_ALLOW_OFFHOST_INTROSPECTION_ACCESS from false to true

### ISSUE THREAD

**Issue by leshik** [aws/amazon-ecs-init#360]
### Summary

Changing `ECS_ALLOW_OFFHOST_INTROSPECTION_ACCESS` from `false` to `true` with the consecutive `systemctl restart ecs` doesn't remove the `iptables` rule which drops packets to port `51678`.

### Description

To change the setting one should keep `ECS_ALLOW_OFFHOST_INTROSPECTION_ACCESS=false`, then stop `ecs` service, change it to `true`, then start the service. Not a very user-friendly flow. Usually, people change configs, then just restart services.

### Expected Behavior

`iptables` rule that drops packets to port `51678` should be removed unconditionally on `ecs` service stop.

### Observed Behavior

`iptables` rule that drops packets to port `51678` is removed on `ecs` service stop only when `ECS_ALLOW_OFFHOST_INTROSPECTION_ACCESS=false`.

### Environment Details

`v1.45.0`

**Comment by fenxiong** [comment]
> iptables rule that drops packets to port 51678 should be removed unconditionally on ecs service stop.

That makes sense. We will work on addressing it.
