### ISSUE TITLE
Setting ECS_ALLOW_OFFHOST_INTROSPECTION_ACCESS=true doesn't appear to work on Amazon Linux 1

### ISSUE THREAD

**Issue by nbrowz** [aws/amazon-ecs-init#368]
### Summary
There's still a rule dropping packets on port 51678 after setting the `ECS_ALLOW_OFFHOST_INTROSPECTION_ACCESS=true` in `/etc/ecs/ecs.config` on Amazon Linux 1.

### Description
After setting `ECS_ALLOW_OFFHOST_INTROSPECTION_ACCESS=true` in the `/etc/ecs/ecs.config` file, there's still a rule dropping packets on port 51678 in Amazon Linux 1. The workaround mentioned in https://github.com/aws/amazon-ecs-init/issues/360 does not appear to work in Amazon Linux 1, but does work for me in Amazon Linux 2. Setting `ECS_ALLOW_OFFHOST_INTROSPECTION_ACCESS=true` seems to not do anything for me on Amazon Linux 1.

I followed these steps:
1. Set `ECS_ALLOW_OFFHOST_INTROSPECTION_ACCESS=false` in `/etc/ecs/ecs.config` (for the workaround mentioned in issue https://github.com/aws/amazon-ecs-init/issues/360)
2. `stop ecs`
3. `start ecs`
4. `iptables -L` shows a rule dropping packets on 51678 as expected
5. `stop ecs`
6. Set `ECS_ALLOW_OFFHOST_INTROSPECTION_ACCESS=true` in `/etc/ecs/ecs.config`
7. `start ecs`
8. `iptables -L` still has a rule dropping packets on 51678

### Expected Behavior

I expect `iptables -L` to show no rules dropping packets on port 51678 after setting `ECS_ALLOW_OFFHOST_INTROSPECTION_ACCESS=true` in `/etc/ecs/ecs.config` and restarting the `ecs` service.

### Observed Behavior

Running `iptables -L` after setting `ECS_ALLOW_OFFHOST_INTROSPECTION_ACCESS=true` in `/etc/ecs/ecs.config` and restarting `ecs` still shows rule:
```
DROP       tcp  --  anywhere             anywhere             tcp dpt:51678
```

### Environment Details

Docker server version: 19.03.6-ce
ecs-init version: 1.46.0-1
AMI: ami-082dd4c61b9c30f7d (amzn-ami-2018.03.20201013-amazon-ecs-optimized, us-east-1)

`curl http://localhost:51678/v1/metadata` returns:
```
{"Cluster":"<omitted>","ContainerInstanceArn":"<omitted>","Version":"Amazon ECS Agent - v1.46.0 (863f2227)"}
```

`cat /etc/os-release` returns:
```
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
```

**Comment by mythri-garaga** [comment]
For AL1, please add `ECS_ALLOW_OFFHOST_INTROSPECTION_ACCESS=true` env in `/etc/init/ecs.conf` as mentioned in https://github.com/aws/amazon-ecs-init/pull/354. 

We will update this information in README.md. Feel free to re-open if you still face this issue.
