### ISSUE TITLE
Docker awslog driver

### ISSUE THREAD

**Issue by aranw** [aws/amazon-ecs-init#40]
Hi I was wondering when ecs might support the docker awslog driver as I've had to a few times now log into ecs cluster servers to pull up docker logs. After digging around into the ECS Optimised OS I came across amazon-ecs-init as the script that starts docker and thought this is the best place to start in adding awslog driver. 

I've looked at a few solutions and would ideally like to awslog driver rather than launching cloudwatch containers to handle it container logging.

**Comment by samuelkarp** [comment]
@aranw Are you looking for the ECS Agent logs to be sent to CloudWatch Logs or for containers you're running through ECS?

**Comment by aranw** [comment]
I'm wanting the container logs to be sent to CloudWatch. I'm guessing the best way to do that is via the docker awslogs logging driver.

**Comment by samuelkarp** [comment]
@aranw We've launched this feature with version [1.9.0](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.9.0) of the ECS agent.
