### ISSUE TITLE
Configurable ecs-agent image version

### ISSUE THREAD

**Issue by tomassejkora** [aws/amazon-ecs-init#406]
### Summary
Enhancement request: Configurable ecs-agent image version

### Description
We would like to have an option to override hard-coded default [ecs-agent version](https://github.com/aws/amazon-ecs-init/blob/5cd4f2cf8348504c8443a21ee507f6ca6f61b065/ecs-init/config/common.go#L33) set to the "latest" in order to we can lock ecs-agent version.

### Expected Behavior
ecs-agent version should be configurable in order to we can lock version and test it pre-prod environments first. With the "latest" tag it may happen that version is accidentally upgraded in production environment under certain conditions.

Please let me know if there is already such option and we overlooked it.

**Comment by mssrivas** [comment]
Hi, thankyou for raising this issue. To understand more, we would like some information. Do you use ECS Optimized AMI or work with custom amis in general?

**Comment by tomassejkora** [comment]
Hi,

Thank you for  the response!

Yes we use ECS Optimized AMI with some tiny customization in user data  and we do daily restart of ecs-agent due to some stability issues.

Freezing AMI doesn't help because in a rare case docker pulls the latest ecs-agent image during ecs-agent restart and the agent version is upgraded without any notice.

**Comment by Realmonia** [comment]
Hi @tomassejkora sorry for the late response, I tried to reproduce the issue but it seems the agent version is not updated with restart. Is it only happening to some specific legacy ecs agent versions? Do you see it happen with recent releases of ecs agent?

**Comment by tomassejkora** [comment]
Hi @Realmonia, no problem. We regularly upgrade ecs agent and I couldn't see any case at least last 6 months. I checked agent versions in production today and it's consistent so maybe it was fixed.

**Comment by Realmonia** [comment]
Thanks for the response! I will close this issue then.
