### ISSUE TITLE
1.53.0 not availalbe as rpm

### ISSUE THREAD

**Issue by zbintliff** [aws/amazon-ecs-init#426]
### Summary
Hello! Just wondering when the latest version will be made available as an RPM

### Description
Currently latest version available as an rpm in the `amz2extra-ecs` repo is 1.52.1 

### Expected Behavior
Latest available will be 1.53.0

### Supporting Log Snippets
# 
```
$ yum clean all && yum list ecs-init
Loaded plugins: priorities, update-motd, upgrade-helper
Cleaning repos: amzn2-core amzn2extra-ecs 
Available Packages
ecs-init.x86_64                                                                                1.52.1-1.amzn2                                                                                amzn2extra-ecs
```

**Comment by sparrc** [comment]
The AL repos are usually behind and they are not directly controlled by our team. Unfortunately you will need to wait until Amazon Linux updates the ecs-init version in their repos. The only workaround would be to terminate your instance and launch with the latest AMI.
