### ISSUE TITLE
Running "make deb" or "make generic-rpm" does not package amazon-ecs-volume-plugin

### ISSUE THREAD

**Issue by dennisconrad** [aws/amazon-ecs-init#431]
### Summary
Running `make deb` or `make generic-rpm` does not package the amazon-ecs-volume-plugin.

NB: `make generic-rpm` was not working at all on Red Hat Enterprise Linux 8.4; this PR fixes this as well.

### Description
When building a generic Debian package via `make deb` or a generic RPM package via `make generic-rpm`, the resulting package does not include the amazon-ecs-volume-plugin binary and startup scripts.

### Expected Behavior
When building a generic Debian package via `make deb` or a generic RPM package via `make generic-rpm`, the resulting package **should** include the amazon-ecs-volume-plugin binary and startup scripts.

### Observed Behavior
When building a generic Debian package via `make deb` or a generic RPM package via `make generic-rpm`, the resulting package **does not** include the amazon-ecs-volume-plugin binary and startup scripts.

### Environment Details
Ubuntu 18.04 Bionic
Red Hat Enterprise Linux 8.4

**Comment by dennisconrad** [comment]
Fixed by: https://github.com/aws/amazon-ecs-init/pull/432

**Comment by Realmonia** [comment]
PR is merged. Close this issue. Thanks for the contribution!
