### ISSUE TITLE
amazon-ecs-volume-plugin.service is missing in SLES 15 SP2 amazon-ecs-init 1.53 version

### ISSUE THREAD

**Issue by viccsjain** [aws/amazon-ecs-init#465]
### Description
We are installing this agent on our EC2 machine which runs on SUSE15 SP2. 
We wanted to configure EFS on this machine, but it gives error that amazon-ecs-volume-plugin is missing. 
We did a rpm -ql on rpm, and it does not have service file for that while Makefile do have entry for that.

```
XXX:~/vikram # rpm -ql amazon-ecs-init-1.53.0-27.1.x86_64
/etc/ecs
/etc/ecs/ecs.config
/etc/ecs/ecs.config.json
/usr/lib/systemd/system/amazon-ecs.service
/usr/sbin/amazon-ecs-init
/usr/share/doc/packages/amazon-ecs-init
/usr/share/doc/packages/amazon-ecs-init/CONTRIBUTING.md
/usr/share/doc/packages/amazon-ecs-init/LICENSE
/usr/share/doc/packages/amazon-ecs-init/NOTICE
/usr/share/doc/packages/amazon-ecs-init/README.md
/usr/share/man/man1/amazon-ecs-init.1.gz
/var/cache/ecs
/var/cache/ecs/ecs-agent.tar
/var/cache/ecs/state
```

### Expected Behavior
I was expecting this agent should also install amazon-ecs-volume-plugin.service so that EFS can be configured on machine.

**Comment by Realmonia** [comment]
This would be fixed by https://github.com/aws/amazon-ecs-init/pull/478. There was a miss in the previous release and we rolled back the change once. It will be updated soon once the PR is merged. Thanks!

**Comment by Realmonia** [comment]
The change is merged. It should be fixed. Feel free to reopen if you see this happen again.
