### ISSUE TITLE
DOC : Explain how to change Cluster attachment

### ISSUE THREAD

**Issue by jmcollin78** [aws/amazon-ecs-init#62]
ie. remove /var/lib/data/ecs*.json
and restart ecs

**Comment by samuelkarp** [comment]
@jmcollin78 Thanks for opening this.  In general, we would not suggest changing the cluster of an existing instance as you'll lose all the information that is related to tasks that instance has already run (old containers, images, etc).  Instead, we'd recommend launching a new instance with the intended cluster configured through user-data as is [documented here](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_container_instance.html).
