### ISSUE TITLE
scripts/update-version.sh modifies git-managed files

### ISSUE THREAD

**Issue by nmeyerhans** [aws/amazon-ecs-init#67]
`update-version.sh` is used to update various references to the ecs-init version in source code. One thing it does is store the short sha of the current HEAD in `ecs-init/version/version.go`. However, because this file is owned by git, any changes to the file are immediately invalid because the sha referenced by HEAD changes.

We could either stop tracking version.go and ensure that it gets generated at build time, or come up with some other mechanism to inject the current sha that doesn't involve modifying files (e.g. reading from some environment variable or injecting the output of some command).

**Comment by samuelkarp** [comment]
I'm okay in general with modifying git-managed files, as long as the file that is checked in to git doesn't contain references that are invalid.  In the ECS agent, we manage this by having the file set the git sha to `UNKNOWN` when checked in, but set to the real sha during builds.

The other way that people typically do things like this with Go + git is by setting the value of a variable at build time with a linker option (something like `go build -ldflags "-X version.GitSha=${SHA}"`).  I'm not terribly opposed to this pattern either, but if we want to switch here I'd prefer that we switch in our other projects too (consistency is important).

**Comment by samuelkarp** [comment]
Fixed by https://github.com/aws/amazon-ecs-init/pull/91.
