### ISSUE TITLE
RHEL 7 no package ecs-init found

### ISSUE THREAD

**Issue by dshin192** [aws/amazon-ecs-init#69]
Not sure if I am missing a yum repository in my configs but I am getting "no package ecs-init available". I am using RHEL 7.2. Or should I use ecs agent from docker instead?

**Comment by samuelkarp** [comment]
Hi @dshin192,

The `ecs-init` package is not available for RHEL today.  You can install the ECS agent on RHEL by following the ["To install the Amazon ECS container agent on a non-Amazon Linux EC2 instance" section of our documentation](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-install.html).

Thanks!
Sam

**Comment by samuelkarp** [comment]
@sumitag We have not published ecs-init for RHEL.

**Comment by demitriusmac** [comment]
Hi guys... is there still no way to get ecs-init running on RHEL 7?
