### ISSUE TITLE
sudo start and stop ecs hangs

### ISSUE THREAD

**Issue by tcco** [aws/amazon-ecs-init#74]
I have ssh'd into a docker optimized linux distribution and tried to run both sudo start ecs and sudo stop ecs. 

Both of which never finish processing. I was curious if there are any other necessary steps to be able to run these commands.

**Comment by samuelkarp** [comment]
> I was curious if there are any other necessary steps to be able to run these commands.

If you're using the ECS-optimized AMI, there are no extra steps.

The only thing I can think of offhand that would cause a hanging behavior would be something wrong with the Docker daemon (both `start ecs` and `stop ecs` interact with Docker).  Are you able to run `docker ps` on the instance or does that hang as well?

**Comment by benfortuna** [comment]
I am also getting this behaviour. ```docker ps|info``` also hangs.

Same behaviour after the following:

`
$ sudo service docker restart
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
Stopping docker:                                           [  OK  ]
Starting docker:        .                                  [  OK  ]`

**Comment by nrcxcia** [comment]
I am also seeing this behavior, it causes some instances to fail to join the ecs cluster

**Comment by spovisenko** [comment]
I had the same problem. I've checked clusters EC2 target instance and found that **Agent Connected** is **false**. Via SSH I performed next command on my problem instance:
- Execute `sudo yum update -y ecs-init`
- Docker was hanging too, so I've checked docker's log: `cat var/log/docker`  and found many warning like this:

> time="2017-04-11T09:46:39.666741390Z" level=info msg="libcontainerd: new containerd process, pid: 2565" 
time="2017-04-11T09:46:39.673254362Z" level=fatal msg="open /var/run/docker/libcontainerd/containerd/7c42eac12e10353bb454e39f3c0474135fd43d968403305949fa94acb9c5f01e/state.json: no such file or directory" 

- clean dir `/var/run/docker/libcontainerd/containerd/`  exec: `rm -rf  /var/run/docker/libcontainerd/containerd/`
- `service docker stop`
- `service docker start`
- `service docker status` should output `docker (pid  xxxx) is running...`
- `sudo reboot`
- check your EC2 instance via console, **Agent Connected** should be **true** and task is runing (is desired count of tasks > 0)

Done

**Comment by samuelkarp** [comment]
@tcco We haven't heard from you in a while, so I'm closing this issue.  If anyone runs into issues here again, please feel free to open a new issue.  We'll likely ask you to run the [ECS logs collector](https://github.com/awslabs/ecs-logs-collector) and send the file it creates to us.  Thanks!
