### ISSUE TITLE
Start ecs-agent with --userns=host

### ISSUE THREAD

**Issue by richardpen** [aws/amazon-ecs-init#76]
Original post: aws/amazon-ecs-agent/issues/668
Pull request: #73
Docker 1.11 added option to disable user namespace per container with `--userns=host`, add this option to ensure "ecs-init" can start the "ecs-agent" when user namespace is enabled in docker.

**Comment by rickard-von-essen** [comment]
This was fixed in 60f297e34104d45bafc75f7915f7c569cc941248

**Comment by samuelkarp** [comment]
@rickard-von-essen Yep, thanks!
