### ISSUE TITLE
Missing latest in Amazon Linux repositories

### ISSUE THREAD

**Issue by arikfr** [aws/amazon-ecs-init#86]
I'm using the latest Amazon Linux AMI, but when I try to install `ecs-init` it only finds version 1.14.0 instead of 1.14.1.

When running `yum --showduplicates list ecs-init` this is what I get:

```
Loaded plugins: priorities, update-motd, upgrade-helper
Installed Packages
ecs-init.x86_64                                      1.14.0-2.amzn1                                      @amzn-updates
Available Packages
ecs-init.x86_64                                      1.12.2-1.amzn1                                      amzn-main
ecs-init.x86_64                                      1.13.0-1.amzn1                                      amzn-updates
ecs-init.x86_64                                      1.13.1-1.amzn1                                      amzn-updates
ecs-init.x86_64                                      1.13.1-2.amzn1                                      amzn-updates
ecs-init.x86_64                                      1.14.0-1.amzn1                                      amzn-updates
ecs-init.x86_64                                      1.14.0-2.amzn1                                      amzn-updates
```

I tried updating the repos but it didn't help. Am I missing something obvious or 1.14.1 wasn't pushed to the repository?

**Comment by jhaynes** [comment]
Hi @arikfr 

We're aware of the issue and working to fix it. I'll update the ticket as soon as it is resolved. In the mean time, the latest ecs-optimized AMI has the most recent 1.14.1 ecs-init and ecs-agent pre installed. You can find the specific ami ids [here](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI_launch_latest.html).

**Comment by arikfr** [comment]
Thanks, @jhaynes . Unfortunately I can't use the ecs-optimized AMI, as its networking configuration isn't compatible with Redshift.

When building our own AMI, we apply the following network changes and then install Docker & ecs-init.

```bash
ip link set dev eth0 mtu 1500
echo "supersede interface-mtu 1500;" >> /etc/dhcp/dhclient.conf
/sbin/sysctl -w net.ipv4.tcp_keepalive_time=200 net.ipv4.tcp_keepalive_intvl=200 net.ipv4.tcp_keepalive_probes=5
echo net.ipv4.tcp_keepalive_time=200 >> /etc/sysctl.conf
echo net.ipv4.tcp_keepalive_intvl=200 >> /etc/sysctl.conf
echo net.ipv4.tcp_keepalive_probes=5 >> /etc/sysctl.conf
```

I'm not sure if it makes sense, but if it was possible to apply this to the default ecs-optimized AMI it could save us a lot of hassle :)

**Comment by jhaynes** [comment]
Can you clarify a bit more about why the networking isn't compatible with Redshift? We like to be as compatible as we can!

I can't think of a technical reason why you couldn't send those same commands as user data on our ecs-optimized AMI. Something like:

```
#/bin/bash
ip link set dev eth0 mtu 1500
echo "supersede interface-mtu 1500;" >> /etc/dhcp/dhclient.conf
/sbin/sysctl -w net.ipv4.tcp_keepalive_time=200 net.ipv4.tcp_keepalive_intvl=200 net.ipv4.tcp_keepalive_probes=5
echo net.ipv4.tcp_keepalive_time=200 >> /etc/sysctl.conf
echo net.ipv4.tcp_keepalive_intvl=200 >> /etc/sysctl.conf
echo net.ipv4.tcp_keepalive_probes=5 >> /etc/sysctl.conf
```

If those need to be set before docker starts you can add `#cloud-boothook` as the first line before the `#!`.

**Comment by arikfr** [comment]
The origins for these settings are:

* http://docs.aws.amazon.com/redshift/latest/mgmt/connecting-drop-issues.html
* http://docs.aws.amazon.com/redshift/latest/mgmt/connecting-firewall-guidance.html (while this article refers to connecting from outside of an EC2 instance, we had this issue with EC2 instances as well - probably across regions)

As for using user data: I tried using user data for this, but it didn't work because it had to be done before docker starts and I wasn't aware of `#cloud-boothook`... I will give it a try when I have the time to test it properly 👍 

Thanks!

**Comment by jhaynes** [comment]
Glad to help. You'll want to write your user-data defensively though since that boothook will run on each boot if you're not careful. An example with semaphores is [here](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/http_proxy_config.html).

**Comment by jhaynes** [comment]
ecs-init v1.14.1-1 is now available in our repos.

```
Available Packages
ecs-init.x86_64                                                          1.12.2-1.amzn1                                                          amzn-main    
ecs-init.x86_64                                                          1.13.0-1.amzn1                                                          amzn-updates 
ecs-init.x86_64                                                          1.13.1-1.amzn1                                                          amzn-updates 
ecs-init.x86_64                                                          1.13.1-2.amzn1                                                          amzn-updates 
ecs-init.x86_64                                                          1.14.0-1.amzn1                                                          amzn-updates 
ecs-init.x86_64                                                          1.14.0-2.amzn1                                                          amzn-updates 
ecs-init.x86_64                                                          1.14.1-1.amzn1                                                          amzn-updates 
```

Please feel free to re-open this ticket if the issue persists.
