### ISSUE TITLE
Where do I download this rpm?

### ISSUE THREAD

**Issue by jadekler** [aws/amazon-ecs-init#89]
Why is the rpm not in releases?

**Comment by cabbruzzese** [comment]
@jadekler the RPM is built for Amazon Linux. The agent is already packaged with the ecs Optimized AMIs. If you are not using the optimized AMI the best way to install the agent is through yum with the command ```sudo yum install -y ecs-init``` on Amazon Linux.

More information is available in the ecs agent install [documentation](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-install.html).

What operating system are you targeting? Issue #58 may be helpful if you are not working with Amazon Linux.

**Comment by jhaynes** [comment]
Hi @jadekler, we haven't heard from you in awhile so I'm going to close this. However, if you're still needing guidance, feel free to respond here and re-open the issue.

**Comment by huntercatalan** [comment]
how do you download this RPM on Amazon Linux 2? Yum is not finding it.

**Comment by daytonpa** [comment]
@huntercatalan AWS hasn't realeased it yet, nor have they released a possible release date.  It's a matter of wait-and-see at this point, unfortunately.

**Comment by jahkeup** [comment]
@huntercatalan, @daytonpa there's now an `ecs` extra that provides `ecs-init` on AL2! We have [instructions on installing on an existing AL2 instance](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-install.html#ecs-agent-install-al2) and also on [using the AL2 ECS-Optimized AMI, which is preconfigured for immediate use](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/al2ami-get-latest.html).
