### ISSUE TITLE
Update tests to use the assert package

### ISSUE THREAD

**Issue by vsiddharth** [aws/amazon-ecs-init#98]
Things to do:
* Vendor `github.com/stretchr/testify`
* Update tests to use the above package

**Comment by jy19** [comment]
created PR https://github.com/aws/amazon-ecs-init/pull/282 - this does not cover the entirety of ecs-init package - we're already using testify package in our newer unit tests and moving forward we should use assert/require and change the older unit tests as new features are added.

**Comment by jy19** [comment]
closing this issue as PR has been merged
